kind: Deployment
apiVersion: apps/v1
metadata:
  name: ls-nc
  namespace: ls-nc
  labels:
    app: ls-nc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ls-nc
  template:
    metadata:
      labels:
        app: ls-nc
    spec:
      containers:
        - name: ls-nc
          image: linuxserver/nextcloud
          env:
            - name: TZ
              value: Europe/Madrid
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 443
              protocol: TCP
              name: https
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pvc-config
        - name: data
          persistentVolumeClaim:
            claimName: pvc-data





