kind: Service
apiVersion: v1
metadata:
  name: svc-ls-nc
  namespace: ls-nc
  labels:
    app: ls-nc
spec:
  selector:
    app: ls-nc
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer